modLoader="javafml"
loaderVersion="[45,)"
license="Custom license"

[[mods]]
modId="purecoppertools"
version="1.0.0"
displayName="Pure Copper Tools"
credits="Made by purejosh"
displayURL="https://www.curseforge.com/minecraft/mc-mods/pure-copper-tools-fabric-forge"
logoFile="logo.png"
authors="purejosh"
description="A unique take on copper armor and tools, that just may fit your vibe."

[[dependencies.purecoppertools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




